### ISSUE TITLE
Typo report

### ISSUE THREAD

**Issue by cmsong-shina** [judofyr/spice#1]
Thanks for enjoyable article!

There is a typo.

```diff
-The baseline implementation takes 1.56 _microseconds_ in total to run.
+The baseline implementation takes 1.56 _nanoseconds_ in total to run.
```

**Comment by judofyr** [comment]
It's actually supposed to say microseconds. The whole program takes 1.56 microseconds, but the graph says 1.56 nanoseconds since we're reporting the "per-node" duration. I know it's a bit confusing. I'll rephrase it. Maybe it's easier to just say "The baseline implementation takes a few microseconds" instead. The exact number isn't so important here anyway.
